fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "0.9.0"
    java_ks: "puppetlabs/java_ks"
    postgresql: "puppetlabs/postgresql"
    stdlib: "puppetlabs/stdlib"
  symlinks:
    confluence: "#{source_dir}"
