fixtures:
  forge_modules:
    apache:
      repo: "puppetlabs/apache"
      ref: "0.9.0"
    java_ks: "puppetlabs/java_ks"
    concat: "puppetlabs/concat"
    apt: "puppetlabs/apt"
    postgresql: "puppetlabs/postgresql"
    stdlib: "puppetlabs/stdlib"
    java: "puppetlabs/java"
  symlinks:
    my_module: "#{source_dir}"
