name    'neuccis-confluence'
version '0.1.0'
source ''
author 'ncc@ccs.neu.edu'
license ''
summary ''
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'puppetlabs/postgresql', '>= 3.3.3'
dependency 'puppetlabs/java_ks', '>= 1.2.4'
dependency 'puppetlabs/apache', '>= 0.9.0'
dependency 'puppetlabs/java', '>= 1.1.1'
